if exists('g:vscode')
    " for vscode-neovim
    " https://github.com/asvetliakov/vscode-neovim
    runtime! vscode.vim
else
    " for vim/neovim
    runtime! config/00-settings.vim
    runtime! config/01-plugins.vim
    runtime! config/02-mappings.vim
    runtime! config/03-plugin-settings.vim
    runtime! config/04-color.vim
    runtime! languages/*.vim
    set relativenumber
endif
